/*
 * Ensures Branches and Routes tables (and related) exist on PostgreSQL when AddBranchAndRoute is skipped.
 * Run once at startup after marking AddBranchAndRoute as applied.
 */
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace HexaBill.Api.Shared.Extensions
{
    public static class PostgresBranchesRoutesSchema
    {
        public static async Task EnsureBranchesAndRoutesSchemaAsync(DbContext context, ILogger? logger)
        {
            if (!context.Database.IsNpgsql())
                return;

            try
            {
                // Branches
                await context.Database.ExecuteSqlRawAsync(@"
CREATE TABLE IF NOT EXISTS ""Branches"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""TenantId"" integer NOT NULL,
    ""Name"" character varying(200) NOT NULL,
    ""Address"" character varying(500),
    ""CreatedAt"" timestamp with time zone NOT NULL,
    ""UpdatedAt"" timestamp with time zone,
    CONSTRAINT ""FK_Branches_Tenants_TenantId"" FOREIGN KEY (""TenantId"") REFERENCES ""Tenants""(""Id"") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ""IX_Branches_TenantId"" ON ""Branches"" (""TenantId"");
");

                // Routes (depends on Branches)
                await context.Database.ExecuteSqlRawAsync(@"
CREATE TABLE IF NOT EXISTS ""Routes"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""BranchId"" integer NOT NULL,
    ""TenantId"" integer NOT NULL,
    ""Name"" character varying(200) NOT NULL,
    ""AssignedStaffId"" integer,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    ""UpdatedAt"" timestamp with time zone,
    CONSTRAINT ""FK_Routes_Branches_BranchId"" FOREIGN KEY (""BranchId"") REFERENCES ""Branches""(""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_Routes_Tenants_TenantId"" FOREIGN KEY (""TenantId"") REFERENCES ""Tenants""(""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_Routes_Users_AssignedStaffId"" FOREIGN KEY (""AssignedStaffId"") REFERENCES ""Users""(""Id"") ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS ""IX_Routes_BranchId"" ON ""Routes"" (""BranchId"");
CREATE INDEX IF NOT EXISTS ""IX_Routes_TenantId"" ON ""Routes"" (""TenantId"");
CREATE INDEX IF NOT EXISTS ""IX_Routes_AssignedStaffId"" ON ""Routes"" (""AssignedStaffId"");
");

                // RouteCustomers
                await context.Database.ExecuteSqlRawAsync(@"
CREATE TABLE IF NOT EXISTS ""RouteCustomers"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""RouteId"" integer NOT NULL,
    ""CustomerId"" integer NOT NULL,
    ""AssignedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""FK_RouteCustomers_Routes_RouteId"" FOREIGN KEY (""RouteId"") REFERENCES ""Routes""(""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_RouteCustomers_Customers_CustomerId"" FOREIGN KEY (""CustomerId"") REFERENCES ""Customers""(""Id"") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ""IX_RouteCustomers_RouteId"" ON ""RouteCustomers"" (""RouteId"");
CREATE INDEX IF NOT EXISTS ""IX_RouteCustomers_CustomerId"" ON ""RouteCustomers"" (""CustomerId"");
CREATE UNIQUE INDEX IF NOT EXISTS ""IX_RouteCustomers_RouteId_CustomerId"" ON ""RouteCustomers"" (""RouteId"", ""CustomerId"");
");

                // RouteExpenses
                await context.Database.ExecuteSqlRawAsync(@"
CREATE TABLE IF NOT EXISTS ""RouteExpenses"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""RouteId"" integer NOT NULL,
    ""TenantId"" integer NOT NULL,
    ""Category"" text NOT NULL,
    ""Amount"" numeric(18,2) NOT NULL,
    ""ExpenseDate"" timestamp with time zone NOT NULL,
    ""Description"" character varying(500),
    ""CreatedBy"" integer NOT NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""FK_RouteExpenses_Routes_RouteId"" FOREIGN KEY (""RouteId"") REFERENCES ""Routes""(""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_RouteExpenses_Tenants_TenantId"" FOREIGN KEY (""TenantId"") REFERENCES ""Tenants""(""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_RouteExpenses_Users_CreatedBy"" FOREIGN KEY (""CreatedBy"") REFERENCES ""Users""(""Id"") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ""IX_RouteExpenses_RouteId"" ON ""RouteExpenses"" (""RouteId"");
CREATE INDEX IF NOT EXISTS ""IX_RouteExpenses_TenantId"" ON ""RouteExpenses"" (""TenantId"");
CREATE INDEX IF NOT EXISTS ""IX_RouteExpenses_CreatedBy"" ON ""RouteExpenses"" (""CreatedBy"");
CREATE INDEX IF NOT EXISTS ""IX_RouteExpenses_ExpenseDate"" ON ""RouteExpenses"" (""ExpenseDate"");
");

                // RouteStaff
                await context.Database.ExecuteSqlRawAsync(@"
CREATE TABLE IF NOT EXISTS ""RouteStaff"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""RouteId"" integer NOT NULL,
    ""UserId"" integer NOT NULL,
    ""AssignedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""FK_RouteStaff_Routes_RouteId"" FOREIGN KEY (""RouteId"") REFERENCES ""Routes""(""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_RouteStaff_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users""(""Id"") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ""IX_RouteStaff_RouteId"" ON ""RouteStaff"" (""RouteId"");
CREATE INDEX IF NOT EXISTS ""IX_RouteStaff_UserId"" ON ""RouteStaff"" (""UserId"");
CREATE UNIQUE INDEX IF NOT EXISTS ""IX_RouteStaff_RouteId_UserId"" ON ""RouteStaff"" (""RouteId"", ""UserId"");
");

                // BranchStaff
                await context.Database.ExecuteSqlRawAsync(@"
CREATE TABLE IF NOT EXISTS ""BranchStaff"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""BranchId"" integer NOT NULL,
    ""UserId"" integer NOT NULL,
    ""AssignedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""FK_BranchStaff_Branches_BranchId"" FOREIGN KEY (""BranchId"" ) REFERENCES ""Branches""(""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_BranchStaff_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users""(""Id"") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ""IX_BranchStaff_BranchId"" ON ""BranchStaff"" (""BranchId"");
CREATE INDEX IF NOT EXISTS ""IX_BranchStaff_UserId"" ON ""BranchStaff"" (""UserId"");
CREATE UNIQUE INDEX IF NOT EXISTS ""IX_BranchStaff_BranchId_UserId"" ON ""BranchStaff"" (""BranchId"", ""UserId"");
");

                // Add BranchId and RouteId to Sales if missing
                await context.Database.ExecuteSqlRawAsync(@"
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'Sales' AND column_name = 'BranchId') THEN
        ALTER TABLE ""Sales"" ADD COLUMN ""BranchId"" integer NULL;
        CREATE INDEX IF NOT EXISTS ""IX_Sales_BranchId"" ON ""Sales"" (""BranchId"");
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Sales_Branches_BranchId') THEN
            ALTER TABLE ""Sales"" ADD CONSTRAINT ""FK_Sales_Branches_BranchId"" FOREIGN KEY (""BranchId"") REFERENCES ""Branches""(""Id"") ON DELETE SET NULL;
        END IF;
    END IF;
END $$;
");
                await context.Database.ExecuteSqlRawAsync(@"
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'Sales' AND column_name = 'RouteId') THEN
        ALTER TABLE ""Sales"" ADD COLUMN ""RouteId"" integer NULL;
        CREATE INDEX IF NOT EXISTS ""IX_Sales_RouteId"" ON ""Sales"" (""RouteId"");
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Sales_Routes_RouteId') THEN
            ALTER TABLE ""Sales"" ADD CONSTRAINT ""FK_Sales_Routes_RouteId"" FOREIGN KEY (""RouteId"") REFERENCES ""Routes""(""Id"") ON DELETE SET NULL;
        END IF;
    END IF;
END $$;
");

                logger?.LogInformation("PostgreSQL: Branches/Routes schema ensured (tables and Sales columns).");
            }
            catch (Exception ex)
            {
                logger?.LogWarning(ex, "PostgreSQL: Ensure Branches/Routes schema failed (may already exist): {Message}", ex.Message);
                throw;
            }
        }
    }
}
