-- Migration script to add ProductCategories table and CategoryId to Products
-- This enables product categorization for better organization
-- Date: 2026-02-17

-- Create ProductCategories table
CREATE TABLE IF NOT EXISTS "ProductCategories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" integer NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(200) NULL,
    "ColorCode" character varying(7) NOT NULL DEFAULT '#3B82F6',
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ProductCategories" PRIMARY KEY ("Id")
);

-- Create unique index on TenantId + Name (category names must be unique per tenant)
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProductCategories_TenantId_Name" 
ON "ProductCategories" ("TenantId", "Name");

-- Add CategoryId column to Products table (nullable foreign key)
ALTER TABLE "Products" 
ADD COLUMN IF NOT EXISTS "CategoryId" integer NULL;

-- Create foreign key constraint
ALTER TABLE "Products"
ADD CONSTRAINT "FK_Products_ProductCategories_CategoryId"
FOREIGN KEY ("CategoryId") REFERENCES "ProductCategories" ("Id")
ON DELETE SET NULL; -- Don't delete products when category is deleted, just set CategoryId to NULL

-- Create index on CategoryId for better query performance
CREATE INDEX IF NOT EXISTS "IX_Products_CategoryId" ON "Products" ("CategoryId");

-- Comment
COMMENT ON TABLE "ProductCategories" IS 'Product categories for organizing products (dairy, beverages, snacks, etc.)';
COMMENT ON COLUMN "Products"."CategoryId" IS 'Optional category assignment for product organization';
