-- ============================================================================
-- COMPLETE PRODUCTS MIGRATION - All Product-related schema changes
-- Date: 2026-02-17
-- Description: Adds IsActive, Barcode, CategoryId, ImageUrl fields to Products
--              and creates ProductCategories table
-- PostgreSQL Production Ready - Idempotent (safe to run multiple times)
-- ============================================================================

-- ============================================================================
-- PART 1: Add IsActive field to Products (Soft Delete Support)
-- ============================================================================
DO $$
BEGIN
    -- Add IsActive column if it doesn't exist
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'Products' AND column_name = 'IsActive'
    ) THEN
        ALTER TABLE "Products" 
        ADD COLUMN "IsActive" boolean NOT NULL DEFAULT true;
        
        RAISE NOTICE 'Added IsActive column to Products table';
    ELSE
        RAISE NOTICE 'IsActive column already exists, skipping';
    END IF;
END $$;

-- Create index for IsActive (idempotent)
CREATE INDEX IF NOT EXISTS "IX_Products_IsActive" ON "Products" ("IsActive");

-- Ensure all existing products are active (safety check)
UPDATE "Products" SET "IsActive" = true WHERE "IsActive" IS NULL;

-- Add comment
COMMENT ON COLUMN "Products"."IsActive" IS 'Soft delete flag: false = deactivated (hidden from POS), true = active';

-- ============================================================================
-- PART 2: Add Barcode field to Products
-- ============================================================================
DO $$
BEGIN
    -- Add Barcode column if it doesn't exist
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'Products' AND column_name = 'Barcode'
    ) THEN
        ALTER TABLE "Products" 
        ADD COLUMN "Barcode" character varying(100) NULL;
        
        RAISE NOTICE 'Added Barcode column to Products table';
    ELSE
        RAISE NOTICE 'Barcode column already exists, skipping';
    END IF;
END $$;

-- Create index for Barcode (idempotent)
CREATE INDEX IF NOT EXISTS "IX_Products_Barcode" ON "Products" ("Barcode");

-- Create unique index on Barcode per tenant (idempotent)
-- Drop existing constraint if it exists (to handle re-runs)
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_indexes 
        WHERE indexname = 'IX_Products_TenantId_Barcode'
    ) THEN
        DROP INDEX IF EXISTS "IX_Products_TenantId_Barcode";
    END IF;
END $$;

CREATE UNIQUE INDEX "IX_Products_TenantId_Barcode" 
ON "Products" ("TenantId", "Barcode") 
WHERE "Barcode" IS NOT NULL;

-- Add comment
COMMENT ON COLUMN "Products"."Barcode" IS 'Barcode for POS scanning (EAN-13, UPC, etc.). Optional field.';

-- ============================================================================
-- PART 3: Create ProductCategories table
-- ============================================================================
CREATE TABLE IF NOT EXISTS "ProductCategories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" integer NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(200) NULL,
    "ColorCode" character varying(7) NOT NULL DEFAULT '#3B82F6',
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_ProductCategories" PRIMARY KEY ("Id")
);

-- Create unique index on TenantId + Name (idempotent)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes 
        WHERE indexname = 'IX_ProductCategories_TenantId_Name'
    ) THEN
        CREATE UNIQUE INDEX "IX_ProductCategories_TenantId_Name" 
        ON "ProductCategories" ("TenantId", "Name");
        
        RAISE NOTICE 'Created unique index on ProductCategories (TenantId, Name)';
    ELSE
        RAISE NOTICE 'Index IX_ProductCategories_TenantId_Name already exists, skipping';
    END IF;
END $$;

-- Add comments
COMMENT ON TABLE "ProductCategories" IS 'Product categories for organizing products (dairy, beverages, snacks, etc.)';
COMMENT ON COLUMN "ProductCategories"."TenantId" IS 'Multi-tenant: Tenant that owns this category';
COMMENT ON COLUMN "ProductCategories"."Name" IS 'Category name (unique per tenant)';
COMMENT ON COLUMN "ProductCategories"."Description" IS 'Optional category description';
COMMENT ON COLUMN "ProductCategories"."ColorCode" IS 'Hex color code for UI display (e.g., #3B82F6)';
COMMENT ON COLUMN "ProductCategories"."IsActive" IS 'Soft delete flag: false = deactivated, true = active';

-- ============================================================================
-- PART 4: Add CategoryId foreign key to Products
-- ============================================================================
DO $$
BEGIN
    -- Add CategoryId column if it doesn't exist
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'Products' AND column_name = 'CategoryId'
    ) THEN
        ALTER TABLE "Products" 
        ADD COLUMN "CategoryId" integer NULL;
        
        RAISE NOTICE 'Added CategoryId column to Products table';
    ELSE
        RAISE NOTICE 'CategoryId column already exists, skipping';
    END IF;
END $$;

-- Create foreign key constraint (idempotent)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_name = 'FK_Products_ProductCategories_CategoryId'
    ) THEN
        ALTER TABLE "Products"
        ADD CONSTRAINT "FK_Products_ProductCategories_CategoryId"
        FOREIGN KEY ("CategoryId") REFERENCES "ProductCategories" ("Id")
        ON DELETE SET NULL;
        
        RAISE NOTICE 'Created foreign key constraint FK_Products_ProductCategories_CategoryId';
    ELSE
        RAISE NOTICE 'Foreign key constraint FK_Products_ProductCategories_CategoryId already exists, skipping';
    END IF;
END $$;

-- Create index on CategoryId (idempotent)
CREATE INDEX IF NOT EXISTS "IX_Products_CategoryId" ON "Products" ("CategoryId");

-- Add comment
COMMENT ON COLUMN "Products"."CategoryId" IS 'Optional category assignment for product organization';

-- ============================================================================
-- PART 5: Add ImageUrl field to Products
-- ============================================================================
DO $$
BEGIN
    -- Add ImageUrl column if it doesn't exist
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'Products' AND column_name = 'ImageUrl'
    ) THEN
        ALTER TABLE "Products" 
        ADD COLUMN "ImageUrl" character varying(500) NULL;
        
        RAISE NOTICE 'Added ImageUrl column to Products table';
    ELSE
        RAISE NOTICE 'ImageUrl column already exists, skipping';
    END IF;
END $$;

-- Create partial index for ImageUrl (only on non-null values)
CREATE INDEX IF NOT EXISTS "IX_Products_ImageUrl" 
ON "Products" ("ImageUrl") 
WHERE "ImageUrl" IS NOT NULL;

-- Add comment
COMMENT ON COLUMN "Products"."ImageUrl" IS 'Product image URL (relative path from /uploads/, e.g., products/product_123_guid.jpg)';

-- ============================================================================
-- VERIFICATION: Check all columns exist
-- ============================================================================
DO $$
DECLARE
    missing_columns text[];
BEGIN
    SELECT array_agg(col) INTO missing_columns
    FROM (
        SELECT 'IsActive' AS col WHERE NOT EXISTS (
            SELECT 1 FROM information_schema.columns 
            WHERE table_name = 'Products' AND column_name = 'IsActive'
        )
        UNION ALL
        SELECT 'Barcode' WHERE NOT EXISTS (
            SELECT 1 FROM information_schema.columns 
            WHERE table_name = 'Products' AND column_name = 'Barcode'
        )
        UNION ALL
        SELECT 'CategoryId' WHERE NOT EXISTS (
            SELECT 1 FROM information_schema.columns 
            WHERE table_name = 'Products' AND column_name = 'CategoryId'
        )
        UNION ALL
        SELECT 'ImageUrl' WHERE NOT EXISTS (
            SELECT 1 FROM information_schema.columns 
            WHERE table_name = 'Products' AND column_name = 'ImageUrl'
        )
    ) missing;
    
    IF array_length(missing_columns, 1) > 0 THEN
        RAISE EXCEPTION 'Missing columns: %', array_to_string(missing_columns, ', ');
    ELSE
        RAISE NOTICE '✅ All product columns verified successfully';
    END IF;
END $$;

-- ============================================================================
-- VERIFICATION: Check ProductCategories table exists
-- ============================================================================
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_name = 'ProductCategories'
    ) THEN
        RAISE EXCEPTION 'ProductCategories table was not created';
    ELSE
        RAISE NOTICE '✅ ProductCategories table verified successfully';
    END IF;
END $$;

-- ============================================================================
-- FINAL SUMMARY
-- ============================================================================
DO $$
BEGIN
    RAISE NOTICE '============================================================================';
    RAISE NOTICE '✅ PRODUCTS MIGRATION COMPLETED SUCCESSFULLY';
    RAISE NOTICE '============================================================================';
    RAISE NOTICE 'Added fields to Products table:';
    RAISE NOTICE '  - IsActive (boolean, default true)';
    RAISE NOTICE '  - Barcode (varchar(100), nullable)';
    RAISE NOTICE '  - CategoryId (integer, nullable FK)';
    RAISE NOTICE '  - ImageUrl (varchar(500), nullable)';
    RAISE NOTICE '';
    RAISE NOTICE 'Created table:';
    RAISE NOTICE '  - ProductCategories (with TenantId, Name, Description, ColorCode, IsActive)';
    RAISE NOTICE '';
    RAISE NOTICE 'Created indexes:';
    RAISE NOTICE '  - IX_Products_IsActive';
    RAISE NOTICE '  - IX_Products_Barcode';
    RAISE NOTICE '  - IX_Products_TenantId_Barcode (unique, partial)';
    RAISE NOTICE '  - IX_Products_CategoryId';
    RAISE NOTICE '  - IX_Products_ImageUrl (partial)';
    RAISE NOTICE '  - IX_ProductCategories_TenantId_Name (unique)';
    RAISE NOTICE '============================================================================';
END $$;
