using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HexaBill.Api.Migrations
{
    /// <inheritdoc />
    public partial class AddProductsFeatures : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Use PostgreSQL native IF NOT EXISTS syntax (PostgreSQL 9.6+)
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql(@"ALTER TABLE ""Products"" ADD COLUMN IF NOT EXISTS ""Barcode"" character varying(100) NULL;");
                migrationBuilder.Sql(@"ALTER TABLE ""Products"" ADD COLUMN IF NOT EXISTS ""CategoryId"" integer NULL;");
                migrationBuilder.Sql(@"ALTER TABLE ""Products"" ADD COLUMN IF NOT EXISTS ""ImageUrl"" character varying(500) NULL;");
                migrationBuilder.Sql(@"ALTER TABLE ""Products"" ADD COLUMN IF NOT EXISTS ""IsActive"" boolean NOT NULL DEFAULT false;");
            }
            else
            {
                // SQLite - use standard AddColumn (will be caught by try-catch if exists)
                migrationBuilder.AddColumn<string>(
                    name: "Barcode",
                    table: "Products",
                    type: "TEXT",
                    maxLength: 100,
                    nullable: true);

                migrationBuilder.AddColumn<int>(
                    name: "CategoryId",
                    table: "Products",
                    type: "INTEGER",
                    nullable: true);

                migrationBuilder.AddColumn<string>(
                    name: "ImageUrl",
                    table: "Products",
                    type: "TEXT",
                    maxLength: 500,
                    nullable: true);

                migrationBuilder.AddColumn<bool>(
                    name: "IsActive",
                    table: "Products",
                    type: "INTEGER",
                    nullable: false,
                    defaultValue: false);
            }

            // PROD-15: Create ProductCategories table with provider-specific types
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                // PostgreSQL: Use native types and sequences
                migrationBuilder.Sql(@"
                    CREATE TABLE IF NOT EXISTS ""ProductCategories"" (
                        ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                        ""TenantId"" integer NULL,
                        ""Name"" character varying(100) NOT NULL,
                        ""Description"" character varying(200) NULL,
                        ""ColorCode"" character varying(7) NOT NULL,
                        ""IsActive"" boolean NOT NULL,
                        ""CreatedAt"" timestamp with time zone NOT NULL,
                        ""UpdatedAt"" timestamp with time zone NOT NULL,
                        CONSTRAINT ""PK_ProductCategories"" PRIMARY KEY (""Id"")
                    );
                ");
            }
            else
            {
                // SQLite: Use standard CreateTable with SQLite types
                migrationBuilder.CreateTable(
                    name: "ProductCategories",
                    columns: table => new
                    {
                        Id = table.Column<int>(type: "INTEGER", nullable: false)
                            .Annotation("Sqlite:Autoincrement", true),
                        TenantId = table.Column<int>(type: "INTEGER", nullable: true),
                        Name = table.Column<string>(type: "TEXT", maxLength: 100, nullable: false),
                        Description = table.Column<string>(type: "TEXT", maxLength: 200, nullable: true),
                        ColorCode = table.Column<string>(type: "TEXT", maxLength: 7, nullable: false),
                        IsActive = table.Column<bool>(type: "INTEGER", nullable: false),
                        CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                        UpdatedAt = table.Column<DateTime>(type: "TEXT", nullable: false)
                    },
                    constraints: table =>
                    {
                        table.PrimaryKey("PK_ProductCategories", x => x.Id);
                    });
            }

            migrationBuilder.CreateIndex(
                name: "IX_Products_CategoryId",
                table: "Products",
                column: "CategoryId");

            migrationBuilder.CreateIndex(
                name: "IX_ProductCategories_TenantId_Name",
                table: "ProductCategories",
                columns: new[] { "TenantId", "Name" },
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_Products_ProductCategories_CategoryId",
                table: "Products",
                column: "CategoryId",
                principalTable: "ProductCategories",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Products_ProductCategories_CategoryId",
                table: "Products");

            migrationBuilder.DropTable(
                name: "ProductCategories");

            migrationBuilder.DropIndex(
                name: "IX_Products_CategoryId",
                table: "Products");

            migrationBuilder.DropColumn(
                name: "Barcode",
                table: "Products");

            migrationBuilder.DropColumn(
                name: "CategoryId",
                table: "Products");

            migrationBuilder.DropColumn(
                name: "ImageUrl",
                table: "Products");

            migrationBuilder.DropColumn(
                name: "IsActive",
                table: "Products");
        }
    }
}
